### ISSUE TITLE
Open the maintainer role to people outside of the PrestaShop company

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#11]
Currently, only employees of the PrestaShop company can be maintainer, with the code review and code merge power.

In order to reduce the bottle neck of the code review / merge and also to give more power to companies with other priorities than the PrestaShop company, it is time to open the maintainer role to other people, outside the company.

**Comment by PululuK** [comment]
Hi @ttoine 

The news about ...  🤔 ?

Thanks

**Comment by matks** [comment]
@ttoine will speak about it better than me but to provide a short quick answer: this is a very long project.

Having only employees of the PrestaShop company as maintainers make a lot of things very easy to manage, such as decisions processes, priorities management, resources management (shared resources such as servers or private resources such as time and people).

Opening the maintainer role to people outside of the company requires the company to provide different answers to a lot of topics/questions.

Example: what happens when 2 maintainers disagree ? One wants to do X, the second refuses to do X.

Today the solution is simple: both maintainers are PrestaShop employees, which means their boss is the Core Lead Developer @eternoendless. As employees, we have a contract which states we must follow his orders. So the 2 maintainers explain their POV to him and he decides what we do.

What if tomorrow, the maintainers team has 50% PrestaShop employees and 50% volunteers ? We need another way to make sure everybody follows the Lead Developer decisions because there will be no contract between the volunteers and the company.

These other ways will probably be a set of rule that we will require all maintainers to comply to.

And @ttoine is, among other things, working on this set of rule. @ttoine is doing an amazing work of finding all the issues that opening the maintainer role to people outside of the company will rise and look for the answers. A lot of these topics are already registered into [this board](https://github.com/PrestaShop/open-source/projects/1).

Trust me, the list of these items is veeeeery long ... Opening the maintainer role of an open source project to people outside of the company which founded it is quite tedious, especially for a company like PrestaShop which worked this way - and is used to this way - for years. But @ttoine accepted the challenge 👏 .

**Comment by ttoine** [comment]
Thanks @matks 
The first step is to make a proof of concept with modules that require low tech skills, in order to focus on the governance problems, list them, and find solutions.

Modules are components of the PrestaShop open source project, with their own review and release process. The plan is to start with a small team of identified volunteers around "ps cleaner". And when everything will work well, to extend to other modules and components of the project.

The main challenges appart code contribution are:
- code review by 2 maintainers, that must be the author of the pull request
- quality check before the release, because modules are available on the Addons marketplace and in the back office of thousands of shops.
- establish and document governance rules (roles and how to get them, ...)

Taking the time to this step well is critical. And, considering the current global health crisis, the work on this may be delayed: everybody, including volunteers on this step project might be currently focused on other priorities, like helping the customers to sell online.

**Comment by PululuK** [comment]
Hi @ttoine 

I'm sorry guys! I had ignored the complexity and the work that it requires ... Big up @ttoine and thank you so much @matks

**Comment by ttoine** [comment]
Well, doing open source right is not just putting your code on GitHub, unfortunately ;-)
And, opening the governance is a huge challenge in order to involve people well.

**Comment by PululuK** [comment]
> Well, doing open source right is not just putting your code on GitHub, unfortunately ;-)
> And, opening the governance is a huge challenge in order to involve people well.

I understood correctly and I totally agree!

**Comment by matks** [comment]
> Well, doing open source right is not just putting your code on GitHub, unfortunately ;-)

I've been doing this for years 😱

**Comment by jf-viguier** [comment]
I'm in

**Comment by ttoine** [comment]
Let's read this document:
https://docs.google.com/document/d/1lMu9xYK7nmU2H_uQuyOhzvuRrfaNsruUMcjOCnwUehs/edit?usp=sharing
Some of you already know it.
If you have ideas of other modules that could fit in this program, please add them at the end of this document.

With the covid health crisis, priorities have change for some people, so the project was in standby until volunteers have time again to go ahead on that. Let me know when we can start to work on this again.

**Comment by ttoine** [comment]
Please read https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/ in the devdocs.

I can now close the bug, the way to become a maintainer is published and many contributors applied. On great step for the PrestaShop open source project !!!

**Comment by PululuK** [comment]
> Please read https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/ in the devdocs.
> 
> I can now close the bug, the way to become a maintainer is published and many contributors applied. On great step for the PrestaShop open source project !!!

Thank you @ttoine  !
Great work
