### ISSUE TITLE
As a merchant I want to know what is tracked in the software during modules installation (Prestashop webpage)

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/open-source#166]
As a merchant I want to be informed what data are tracked in the software during modules installation 

## Context

When prestashop is being installed, the project wishes to collect the shop (being installed) URL and the version of PrestaShop being used.
Even if this is compliant with GDPR we wish the user to be fully informed.

## Business rules

During the shop installation (inside installer) a message should warn the user that the shop URL will be collected and user should be given a link to a specific webpage on https://www.prestashop-project.org/

This webpage should be a document that explain : 
1. What data is collected
2. How to turn off the data collection (see https://github.com/PrestaShop/PrestaShop/issues/31627)
3. How user can host its own distribution API (hence removing the link to the webservice collecting the data)

**Comment by matks** [comment]
I can provide a draft :

```
## PrestaShop 8 telemetry

In version {to be completed} PrestaShop software includes a telemetry feature. This article explains the reasons behind, what data is collected and how to disable it.

### Reasons

PrestaShop 8 was a [turning point](https://www.prestashop-project.org/releases/prestashop80/) as the project moves towards company neutrality: the project is mostly free of all company products as well as services. But the removal of plenty links to the PrestaShop company also removed the ability for the project to know what usage is made of its software.

The project being blinded prevents making informed decisions. For example being unable to know if a given version is still used makes the task of choosing whether or not to sunset a given service, needed by that version, very hard to do without reliable data.

### What data is collected

The [ps_distributionapiclient](https://github.com/prestashop/ps_distributionapiclient/) module allows shop to poll the [Distribution API](https://github.com/prestashop/distribution-api/) in order to retrieve informations about latest PrestaShop core releases, latest PrestaShop native module releases and module compatibility ranges.

When such a call is made
- shop version is being sent to Distribution API
- shop URL is being sent to Distribution API

### How to turn off the telemetry

In order to turn off the telemetry, the simplest way is to use environment variable {to be completed} and set it to {to be completed}. This will disable the telemetry feature.

Another way to avoid the above data to be sent is to not use the Distribution API hosted by PrestaShop project. As the Distribution API acts as the data collector, it is possible to host your own instance of [Distribution API](https://github.com/prestashop/distribution-api/) and use it instead of the default API being provided.
```

Please tell me if the above content is correct @PrestaShop/product-team

**Comment by l-delin** [comment]
@matks 

Can you edit the "Reasons" part a bit to comply with the content style guide? (store not shop) :-) Thank you

```
When such a call is made
- Store version is sent to Distribution API
- Store URL is sent to Distribution API
```

**Comment by coffrep** [comment]
Great content @matks , I've juste made a few suggestions =>

## PrestaShop 8 telemetry

In version {to be completed}, PrestaShop software includes a telemetry feature. This article explains the reasons behind this, what data is collected and how to disable it.

### Reasons

PrestaShop 8 was a [turning point](https://www.prestashop-project.org/releases/prestashop80/) as the project moves towards company neutrality: the project is mostly free of all company products as well as services. But the removal of many links to the PrestaShop company also removed the ability for the project to know what usage is made of its software.

The project being blinded prevents making informed decisions. For example, being unable to know if a given version is still used makes the task of choosing whether or not to sunset a given service, needed by that version, very hard to do without reliable data.

### What data is collected

The [ps_distributionapiclient](https://github.com/prestashop/ps_distributionapiclient/) module allows shops to poll the [Distribution API](https://github.com/prestashop/distribution-api/) in order to retrieve information about latest PrestaShop core releases, latest PrestaShop native module releases and module compatibility ranges.

When such a call is made:
- store version is being sent to Distribution API
- store URL is being sent to Distribution API

### How to turn off the telemetry

In order to turn off the telemetry, the simplest way is to use an environment variable {to be completed} and set it to {to be completed}. This will disable the telemetry feature.

Another way to avoid the above data to be sent is to not use the Distribution API hosted by the PrestaShop project. As the Distribution API acts as the data collector, it is possible to host your own instance of [Distribution API](https://github.com/prestashop/distribution-api/) and use it instead of the default API being provided.

**Comment by eternoendless** [comment]
Hey guys, I just discovered this issue so I didn't follow your text to the letter. Feel free to improve my PR as necessary.
