### ISSUE TITLE
I want to be a maintainer

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/open-source#42]
I want to be a maintainer. For modules for start, and why not in the core later when I will learn how to git rebase (private joke for @matks ) ;-)

**I contribute**
- I've already have some merged PR in Prestashop core and modules : http://contributors.prestashop.com/#jf-viguier

**I'm a friend of presta** 
I've lauched the "ecommerce solidaire" initiative with 200 prestashop deployed 
In video : https://youtu.be/UVi9_VwLxlo
In the press "le journal des entreprises" :
https://www.lejournaldesentreprises.com/toulouse/article/coronavirus-des-experts-du-e-commerce-aident-les-tpe-creer-leur-site-marchand-493162
I'm vice president of Friends of Presta french association

**I'm involved in ps events** 
I've organized some events in Toulouse about Prestashop 
- First Symfony/PS masterclass in France :
https://lacantine-toulouse.org/8067/masterclass-developer-prestashop-prise-en-main-du-nouveau-framework-de-la-version-1-7-base-sur-symfony
- Conference on Prestashop 1.7 by myself :
https://lacantine-toulouse.org/7901/afterwork-prestashop

**I craft Prestashop websites since 7 years**
I own Creabilis Agency in Toulouse, we've done some very customized prestashop websites :
https://www.thierry-aime-chocolatier.com/
https://www.declicfitness.com/
https://www.memecosmetics.fr/fr/
https://www.mgirod.com/17566-flyers-a6.html
https://www.unique-editions.com/150-285-livre-personnalise-au-pays-du-pere-noel.html

twitter : https://twitter.com/jfviguier 
linkedin : https://www.linkedin.com/in/jfviguier/

**Comment by Progi1984** [comment]
@jf-viguier Issue transferred to the open source repository.

**Comment by ttoine** [comment]
so, you are mainly interested with modules, right?

**Comment by matks** [comment]
Hi @jf-viguier and thank you for your application 😄 

Following [our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/), now can start discussions with current maintainers on this issue about, among other things, your motivation and skills about the project.

Some maintainers are on holidays right now so we will need them to come back so they can have the chance to chat with you before moving on to the voting phase 😉 please be patient.

> I want to be a maintainer. For modules for start, and why not in the core later when I will learn how to git rebase (private joke for @matks ) ;-)

I will be happy to show you how it's done 😄 it seems scary at first but it's a just a concept a little bit confusing. Once you get it and practice it a bit, it becomes a lot easier.

**Comment by jf-viguier** [comment]
Thanks @matks

**Comment by Progi1984** [comment]
Hi @jf-viguier, Thank you again for your contributions. It's time for questions ;) I begin (and don't worry no bad answers).

- Why do you want to move from the role of contributor to the role of maintainer?
- What do you want to do on modules ? 
- When would you want to go on Core ?
- Have you got some ideas to improve the quality in project (and modules) ?

**Comment by jf-viguier** [comment]
Hi @Progi1984,
>Why do you want to move from the role of contributor to the role of maintainer?

I work every day with marchants of all sizes. I want to impulse my "from the field" point of vue and focus on real word issues. 

> What do you want to do on modules and core ?

I've no plan yet, I will start small and follow core maintainers direction.

> Have you got some ideas to improve the quality in project (and modules) ?

An ecommerce business is not only a prestashop instance but an entire eco-system with modules, specific devs, erp, apis, ... We have to keep in mind, the whole picture to build a better prestashop.
Let's start by an exemple : prestashop database is sometimes very large because of logs, useless old connections, expired cart rules. The ps-cleaner module could make a better job and rotate logs, clean old or useless data.

**Comment by eternoendless** [comment]
Hi @jf-viguier 

Regardless of the motivation boost that comes with the maintainer role, what do you think becoming a maintainer would help you do that you cannot do right now?

I understand you'd like to maintain a module for starters, which one(s) do you have in mind?

**Comment by jf-viguier** [comment]
Hi @eternoendless,
Just to be clear, I don't want extra power on Prestashop core. I'm just following @ttoine project to have some maintainers on small (abandoned ?) modules like ps_cleaner and give some little help.
Like @kpodemski I'd like to have a chance to discuss about future of prestashop with core team and give my "from the field" point of view.
I'm not a "good dev", with perfect skill, I've maybe misunderstood the role of maintainer, so feel free to reject my proposal.

**Comment by jf-viguier** [comment]
We have a meeting saturday with Friends of Presta in Tarn, France. Be me guest if you want to come. I'll be more confortable to discuss all of this face to face with a local crafted beer 🍻

**Comment by matks** [comment]
Hi @jf-viguier,

Thank you for the answers you provided for other topics 😉 

I have a "tough question" now 😅 . One that is worrying me so I think it's important to discuss it.

The question is: **are you ready to accept and deal with the frustration that can come with the maintainer position ?**

Please let me explain what I mean by this. As a open source maintainer, you are very likely to experience many times _frustration and bitterness_.

## Frustration because being maintainer is being part of a group

By becoming a maintainer you will be granted the capability of approving Pull Requests with  a validation asset. Anybody can approve PRs but only maintainers can unlock the "merge" button using their approvals. Right now the Core repository PRs need 2 approvals to be validated and other repositories can use only one.

But becoming a maintainer does not mean you can approve and merge whatever you want. When a PR is validated by maintainer, it enters the QA stage. Also sometimes PRs need to be validated by UX team and/or Product team if it is related to their scope. So a PR can only be merged when all the people in charge have agreed to merge it. 3 teams work on this project 😉 : maintainers, QA team and Product team. We have to work together and we look for consensus.

**Becoming a maintainer does not mean you unlock the ability to decide on the project.** It means you unlock the ability to actively participate, by joining a group. Just like every citizen of a democracy can vote, but only one candidate is chosen at the end of the election (which means the citizens who voted for someone else are disappointed) there will be discussions, changes, PRs, where they will disagreements within the maintainer group.

Some people will approve a PR, other will block it. Most of the times both sides have a good reason 😄 but it's still frustrating . Then a discussion will start and hopefully find a way that pleases everyone... but sometimes it wont end this way and you might get frustrated by the end result.

Becoming a maintainer is really joining a group 😁  it means you have to work with multiple other opinions and people, this can sometimes be quite annoying. Most of the time if we cant get a consensus on something we just dont do it. Obviously we are very open for discussion, but we cannot promise we'll always agree together.

There are multiple other situations that I can think of where a maintainer might be frustrated :
- a PR that you believe is very important - you approve it ; but someone else from the maintainer group is not fine with it so (s)he asks for changes / blocks it
- a PR that you believe is very important (example: a module release) - but because the QA team has other priorities it waits for a very very long time and the PR goes stale
- a PR that seems to be OK but other maintainers are afraid to merge it because it is very hard to make sure 100% it does not introduce unwanted side-effects
- a PR that you believe is very important but introduces a BC break that [other maintainers are unwilling to accept](https://www.snoyman.com/blog/2018/04/stop-breaking-compatibility) (example: upgrade Bootstrap version)
- a PR that you believe is very important to put in the next version but other maintainers want to post-pone it until next version
- a bug that is critical to you but is labeled "minor"

Some real-life examples about that:
- @PierreRambaud could not merge [this PR](https://github.com/PrestaShop/PrestaShop/pull/12824)
- [this PR of mine](https://github.com/PrestaShop/PrestaShop/pull/19277) was post-poned from 1.7.7.x to 1.7.8.x because we wanted to stop burdening the 177 scope even though this topic is important to me

This does not happen every day (😄) but these are real-life scenarios. And because as a maintainer you'll be part of a group, you'll need to comply to the final group decision even if it is against your own opinion. This is sometimes hard to do but this will be required from you to do - just like all of us - because it's in [our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/how-to-become-a-maintainer/).

## Frustration because being maintainer is dealing with people

As a maintainer we work everyday with the prestashop community. Some of them are very nice people and some other ... speak with quite harsh words 😅 (I remember having been called "an idiot", "a fake developer", "a genius" (irony) ...) . Some of them are very skilled and submit PRs without issues and some of them need to be mentored / educated about how an open source project works.

This means that sometimes you'll have discussions that might ignite anger and bitterness.

We have tools to deal with that: we have a [CoC](https://devdocs.prestashop.com/1.7/project/code-of-conduct/), we can lock issues and ban users, but we usually use them as a nice resort. Most of the time we'll try first to understand and help the person even though on the other side, the contributor is not as nice as we are...

This article is a very nice insight about this aspect of the role: https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/

## Frustration because you become a public figure

By becoming a maintainer you'll become an (even more) public figure. Maintainers are the representatives of the PrestaShop project. I dont know if our CoC applies to other media like Twitter or Facebook but basically if the next day you tweet "I really think people who drive red cars are idiots" you might later find people retweeting "PrestaShop project is against people who like red cars" 😅 . So basically you'll have to watch what you say and write when in public because suddenly the PrestaShop brand will be associated to you. You cannot go around and say "PS 1.6 was better" :trollface: 

Sometimes we get some very nasty attacks on social media (I'm thinking obviously about Twitter) but we must refrain ourselves from answering because we have to maintain a composure.

## Conclusion

I hope that I did not kill your motivation 😅 but it's something you'll encounter if you become a maintainer and it's better to know beforehand.

But though it has its downsides, being an open source maintainer has also amazing benefits. It's a rewarding role, you learn a lot, you contribute to something that helps hundred of people and businesses ...

So, back to my question ... are you ready to handle this frustration and bitterness when it comes ? And by "handling" I mean: stay calm, focus on the facts, not the feelings and keep following our CoC:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members
 
If tomorrow you and I we disagree on a Pull Request or an issue, will you be able to "agree to disagree" and let the matter cool off ? What if it happens multiple times on a week, on topics that are dear to you ?

Don't be mad at me 😅 but I remember us having an heavy discussion on [this topic](https://github.com/PrestaShop/PrestaShop/issues/11172) linked to [this PR](https://github.com/PrestaShop/PrestaShop/pull/12878). At this time through your writing I believe you were quite unhappy with our view of the topic (although later we changed our mind 🙏 so the topic started badly but it ended well). This situation might happen again but this time, if you're a maintainer, you'll have more constraints. Is that OK for you ? 😉

**Comment by jf-viguier** [comment]
Thanks @matks for your concern, I'll take some time to think about it.

**Comment by matks** [comment]
Hi @jf-viguier we think the voting could happen this week, did you have some time to think about my "tough question" 😅 ?

**Comment by jf-viguier** [comment]
I close this issue for now.
